### ISSUE TITLE
Description list pattern multiple definition per term

### ISSUE THREAD

**Issue by peterserfozo** [openeuropa/oe_bootstrap_theme#255]
In `description_list.ui.patterns.yml` the definitions are not displayed in this case (multiple definitions):
```
- term:
  - label:
    - '#markup': 'A label with <em>some</em> markup.'
  definition:
    - 'First description of third term text goes here.'
    - 'Second description of third term text goes here.'
``` 

As I see the problem is in `bcl-description-list.html.twig:126`:
```
{%- else -%}
  {{- _definition.label -}}
{%- endif -%}
```
